apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loadgen
  labels:
    app: loadgen
spec:
  serviceName: "loadgen"
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      name: loadgen
      labels:
        app: loadgen
    spec:
      containers:
      - name: infinite-calls
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://php-apache-svc.apache.svc.cluster.local; done"
